apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dash
  namespace: $(kubernetes-namespace)
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dash
  template:
    metadata:
      labels:
        app: dash
    spec:
      initContainers:
      - name: init-git
        image: alpine/git:latest
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: init-script
          mountPath: "/scripts"
        - name: data
          mountPath: /data
        command: [ "sh", "-c", "tail -f /dev/null # DEBUG=1 /scripts/init_dashboard_version.sh /data" ]
      containers:
      - name: container
        image: 579478677147.dkr.ecr.eu-central-1.amazonaws.com/ded/dash:$(Build.BuildId)
        ports:
        - containerPort: 80
          name: web
        env:
        - name: DASH__APIKEY
          value: $(apikey)
        - name: DASH__ROOT
          value: /data
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: init-script
        configMap:
          name: init-script
      - name: data
        emptyDir: {}
