apiVersion: v1
kind: Service
metadata:
  name: dash
  annotations:
    prometheus.io/scrape: 'true'
spec:
  selector:
    app: dash
  ports:
  - name: external
    port: 80
    targetPort: web
  type: ClusterIP
